# Air configuration for hot reloading
# See: https://github.com/cosmtrek/air

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./build/zeroui"
  cmd = "go build -ldflags=\"-w -s\" -o ./build/zeroui ."
  delay = 1000
  exclude_dir = ["build", "tmp", "vendor", "testdata", "coverage", ".git", "docs"]
  exclude_file = []
  exclude_regex = ["_test.go", "\\.pb\\.go$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json", "toml"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = ["go fmt ./...", "go mod tidy"]
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true