# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  # Duplication detection
  dupl:
    threshold: 100

  # Error checks
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Sscanf
      - os.Remove
      - os.RemoveAll
      - os.Rename
      - (*os.File).Close
      - (*os.File).Sync
      - (*bufio.Writer).Flush

  # gofmt settings
  gofmt:
    simplify: true

  # Security
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input
      - G404 # Weak random number generator (math/rand is used for UI effects)
      - G301 # Directory permissions (0755 is standard for config dirs)
      - G302 # File permissions
      - G306 # WriteFile permissions

  # Unused code
  unused:
    check-exported: false

  # Whitespace
  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    # Core Go linters
    # - errcheck # Disabled due to high volume of existing unchecked errors
    # - gosimple # Disabled due to conflicts/noise
    - govet
    - ineffassign
    # - staticcheck # Disabled due to noise
    - typecheck

    # Code quality
    - gofmt
    - gosec
    - unconvert
    - whitespace

    # Style
    - gofumpt
    # - godox
    - nolintlint

    # Bugs
    - bodyclose
    - rowserrcheck
    - sqlclosecheck

  disable:
    - cyclop
    - revive
    - gocritic
    - exhaustive
    - forcetypeassert
    - godot
    - nlreturn
    - wsl
    - dupl
    - unused
    - staticcheck
    - goimports
    - misspell
    - gosimple
    - errcheck
    - godox
    # Deprecated/removed linters commented out or removed
    # - exhaustivestruct
    # - gomnd
    # - interfacer
    # - maligned
    # - scopelint
    # - exportloopref

issues:
  uniq-by-line: true
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck

    # Ignore errors in migrations
    - path: migrations/
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: warning
