// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: internal/plugins/rpc/protocol.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *PluginInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetInfo() *PluginInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type DetectConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectConfigRequest) Reset() {
	*x = DetectConfigRequest{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectConfigRequest) ProtoMessage() {}

func (x *DetectConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectConfigRequest.ProtoReflect.Descriptor instead.
func (*DetectConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{2}
}

type DetectConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigInfo            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectConfigResponse) Reset() {
	*x = DetectConfigResponse{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectConfigResponse) ProtoMessage() {}

func (x *DetectConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectConfigResponse.ProtoReflect.Descriptor instead.
func (*DetectConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *DetectConfigResponse) GetConfig() *ConfigInfo {
	if x != nil {
		return x.Config
	}
	return nil
}

type ParseConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseConfigRequest) Reset() {
	*x = ParseConfigRequest{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseConfigRequest) ProtoMessage() {}

func (x *ParseConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseConfigRequest.ProtoReflect.Descriptor instead.
func (*ParseConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *ParseConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ParseConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ConfigData            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseConfigResponse) Reset() {
	*x = ParseConfigResponse{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseConfigResponse) ProtoMessage() {}

func (x *ParseConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseConfigResponse.ProtoReflect.Descriptor instead.
func (*ParseConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *ParseConfigResponse) GetData() *ConfigData {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          *ConfigData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteConfigRequest) Reset() {
	*x = WriteConfigRequest{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfigRequest) ProtoMessage() {}

func (x *WriteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfigRequest.ProtoReflect.Descriptor instead.
func (*WriteConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *WriteConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteConfigRequest) GetData() *ConfigData {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteConfigResponse) Reset() {
	*x = WriteConfigResponse{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfigResponse) ProtoMessage() {}

func (x *WriteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfigResponse.ProtoReflect.Descriptor instead.
func (*WriteConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{7}
}

type ValidateFieldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateFieldRequest) Reset() {
	*x = ValidateFieldRequest{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateFieldRequest) ProtoMessage() {}

func (x *ValidateFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateFieldRequest.ProtoReflect.Descriptor instead.
func (*ValidateFieldRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateFieldRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidateFieldRequest) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type ValidateFieldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateFieldResponse) Reset() {
	*x = ValidateFieldResponse{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateFieldResponse) ProtoMessage() {}

func (x *ValidateFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateFieldResponse.ProtoReflect.Descriptor instead.
func (*ValidateFieldResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateFieldResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateFieldResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ConfigData            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateConfigRequest) GetData() *ConfigData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateConfigResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{12}
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ConfigMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *GetSchemaResponse) GetMetadata() *ConfigMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SupportsFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       string                 `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportsFeatureRequest) Reset() {
	*x = SupportsFeatureRequest{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportsFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportsFeatureRequest) ProtoMessage() {}

func (x *SupportsFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportsFeatureRequest.ProtoReflect.Descriptor instead.
func (*SupportsFeatureRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *SupportsFeatureRequest) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

type SupportsFeatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supported     bool                   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportsFeatureResponse) Reset() {
	*x = SupportsFeatureResponse{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportsFeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportsFeatureResponse) ProtoMessage() {}

func (x *SupportsFeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportsFeatureResponse.ProtoReflect.Descriptor instead.
func (*SupportsFeatureResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *SupportsFeatureResponse) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,6,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginInfo) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PluginInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ConfigInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Discovered    bool                   `protobuf:"varint,3,opt,name=discovered,proto3" json:"discovered,omitempty"`
	Suggestions   []string               `protobuf:"bytes,4,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigInfo) Reset() {
	*x = ConfigInfo{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigInfo) ProtoMessage() {}

func (x *ConfigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigInfo.ProtoReflect.Descriptor instead.
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *ConfigInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ConfigInfo) GetDiscovered() bool {
	if x != nil {
		return x.Discovered
	}
	return false
}

func (x *ConfigInfo) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *ConfigInfo) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

type ConfigData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*anypb.Any  `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      *ConfigMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigData) Reset() {
	*x = ConfigData{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigData) ProtoMessage() {}

func (x *ConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigData.ProtoReflect.Descriptor instead.
func (*ConfigData) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{18}
}

func (x *ConfigData) GetFields() map[string]*anypb.Any {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ConfigData) GetMetadata() *ConfigMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ConfigMetadata struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Fields        map[string]*FieldMetadata `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Presets       map[string]*PresetData    `protobuf:"bytes,2,rep,name=presets,proto3" json:"presets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Schema        *SchemaInfo               `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMetadata) Reset() {
	*x = ConfigMetadata{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMetadata) ProtoMessage() {}

func (x *ConfigMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMetadata.ProtoReflect.Descriptor instead.
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{19}
}

func (x *ConfigMetadata) GetFields() map[string]*FieldMetadata {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ConfigMetadata) GetPresets() map[string]*PresetData {
	if x != nil {
		return x.Presets
	}
	return nil
}

func (x *ConfigMetadata) GetSchema() *SchemaInfo {
	if x != nil {
		return x.Schema
	}
	return nil
}

type FieldMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DefaultValue  *anypb.Any             `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Validation    *Validation            `protobuf:"bytes,5,opt,name=validation,proto3" json:"validation,omitempty"`
	Options       []string               `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMetadata) Reset() {
	*x = FieldMetadata{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMetadata) ProtoMessage() {}

func (x *FieldMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMetadata.ProtoReflect.Descriptor instead.
func (*FieldMetadata) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{20}
}

func (x *FieldMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldMetadata) GetDefaultValue() *anypb.Any {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *FieldMetadata) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldMetadata) GetValidation() *Validation {
	if x != nil {
		return x.Validation
	}
	return nil
}

func (x *FieldMetadata) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *FieldMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Validation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Min           *anypb.Any             `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           *anypb.Any             `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
	Enum          []string               `protobuf:"bytes,4,rep,name=enum,proto3" json:"enum,omitempty"`
	Custom        string                 `protobuf:"bytes,5,opt,name=custom,proto3" json:"custom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validation) Reset() {
	*x = Validation{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validation) ProtoMessage() {}

func (x *Validation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validation.ProtoReflect.Descriptor instead.
func (*Validation) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{21}
}

func (x *Validation) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Validation) GetMin() *anypb.Any {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *Validation) GetMax() *anypb.Any {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *Validation) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *Validation) GetCustom() string {
	if x != nil {
		return x.Custom
	}
	return ""
}

type PresetData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Values        map[string]*anypb.Any  `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetData) Reset() {
	*x = PresetData{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetData) ProtoMessage() {}

func (x *PresetData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetData.ProtoReflect.Descriptor instead.
func (*PresetData) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{22}
}

func (x *PresetData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PresetData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PresetData) GetValues() map[string]*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *PresetData) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SchemaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Compatible    bool                   `protobuf:"varint,3,opt,name=compatible,proto3" json:"compatible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaInfo) Reset() {
	*x = SchemaInfo{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaInfo) ProtoMessage() {}

func (x *SchemaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaInfo.ProtoReflect.Descriptor instead.
func (*SchemaInfo) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{23}
}

func (x *SchemaInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SchemaInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *SchemaInfo) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_rpc_protocol_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_internal_plugins_rpc_protocol_proto_rawDescGZIP(), []int{24}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_internal_plugins_rpc_protocol_proto protoreflect.FileDescriptor

const file_internal_plugins_rpc_protocol_proto_rawDesc = "" +
	"\n" +
	"#internal/plugins/rpc/protocol.proto\x12\x03rpc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\x10\n" +
	"\x0eGetInfoRequest\"6\n" +
	"\x0fGetInfoResponse\x12#\n" +
	"\x04info\x18\x01 \x01(\v2\x0f.rpc.PluginInfoR\x04info\"\x15\n" +
	"\x13DetectConfigRequest\"?\n" +
	"\x14DetectConfigResponse\x12'\n" +
	"\x06config\x18\x01 \x01(\v2\x0f.rpc.ConfigInfoR\x06config\"(\n" +
	"\x12ParseConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\":\n" +
	"\x13ParseConfigResponse\x12#\n" +
	"\x04data\x18\x01 \x01(\v2\x0f.rpc.ConfigDataR\x04data\"M\n" +
	"\x12WriteConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.rpc.ConfigDataR\x04data\"\x15\n" +
	"\x13WriteConfigResponse\"X\n" +
	"\x14ValidateFieldRequest\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\"C\n" +
	"\x15ValidateFieldResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"<\n" +
	"\x15ValidateConfigRequest\x12#\n" +
	"\x04data\x18\x01 \x01(\v2\x0f.rpc.ConfigDataR\x04data\"\\\n" +
	"\x16ValidateConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.rpc.ValidationErrorR\x06errors\"\x12\n" +
	"\x10GetSchemaRequest\"D\n" +
	"\x11GetSchemaResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.rpc.ConfigMetadataR\bmetadata\"2\n" +
	"\x16SupportsFeatureRequest\x12\x18\n" +
	"\afeature\x18\x01 \x01(\tR\afeature\"7\n" +
	"\x17SupportsFeatureResponse\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\"\xb1\x02\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12\x1f\n" +
	"\vapi_version\x18\x06 \x01(\tR\n" +
	"apiVersion\x129\n" +
	"\bmetadata\x18\a \x03(\v2\x1d.rpc.PluginInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\n" +
	"ConfigInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1e\n" +
	"\n" +
	"discovered\x18\x03 \x01(\bR\n" +
	"discovered\x12 \n" +
	"\vsuggestions\x18\x04 \x03(\tR\vsuggestions\x12?\n" +
	"\rlast_modified\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\"\xc3\x01\n" +
	"\n" +
	"ConfigData\x123\n" +
	"\x06fields\x18\x01 \x03(\v2\x1b.rpc.ConfigData.FieldsEntryR\x06fields\x12/\n" +
	"\bmetadata\x18\x02 \x01(\v2\x13.rpc.ConfigMetadataR\bmetadata\x1aO\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\xca\x02\n" +
	"\x0eConfigMetadata\x127\n" +
	"\x06fields\x18\x01 \x03(\v2\x1f.rpc.ConfigMetadata.FieldsEntryR\x06fields\x12:\n" +
	"\apresets\x18\x02 \x03(\v2 .rpc.ConfigMetadata.PresetsEntryR\apresets\x12'\n" +
	"\x06schema\x18\x03 \x01(\v2\x0f.rpc.SchemaInfoR\x06schema\x1aM\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.rpc.FieldMetadataR\x05value:\x028\x01\x1aK\n" +
	"\fPresetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.rpc.PresetDataR\x05value:\x028\x01\"\xfb\x01\n" +
	"\rFieldMetadata\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\rdefault_value\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\fdefaultValue\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12/\n" +
	"\n" +
	"validation\x18\x05 \x01(\v2\x0f.rpc.ValidationR\n" +
	"validation\x12\x18\n" +
	"\aoptions\x18\x06 \x03(\tR\aoptions\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"\xa2\x01\n" +
	"\n" +
	"Validation\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12&\n" +
	"\x03min\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03min\x12&\n" +
	"\x03max\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x03max\x12\x12\n" +
	"\x04enum\x18\x04 \x03(\tR\x04enum\x12\x16\n" +
	"\x06custom\x18\x05 \x01(\tR\x06custom\"\xdc\x01\n" +
	"\n" +
	"PresetData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\x06values\x18\x03 \x03(\v2\x1b.rpc.PresetData.ValuesEntryR\x06values\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"b\n" +
	"\n" +
	"SchemaInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x1e\n" +
	"\n" +
	"compatible\x18\x03 \x01(\bR\n" +
	"compatible\"\x81\x01\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12*\n" +
	"\x05value\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x05value2\xaa\x04\n" +
	"\fConfigPlugin\x124\n" +
	"\aGetInfo\x12\x13.rpc.GetInfoRequest\x1a\x14.rpc.GetInfoResponse\x12C\n" +
	"\fDetectConfig\x12\x18.rpc.DetectConfigRequest\x1a\x19.rpc.DetectConfigResponse\x12@\n" +
	"\vParseConfig\x12\x17.rpc.ParseConfigRequest\x1a\x18.rpc.ParseConfigResponse\x12@\n" +
	"\vWriteConfig\x12\x17.rpc.WriteConfigRequest\x1a\x18.rpc.WriteConfigResponse\x12F\n" +
	"\rValidateField\x12\x19.rpc.ValidateFieldRequest\x1a\x1a.rpc.ValidateFieldResponse\x12I\n" +
	"\x0eValidateConfig\x12\x1a.rpc.ValidateConfigRequest\x1a\x1b.rpc.ValidateConfigResponse\x12:\n" +
	"\tGetSchema\x12\x15.rpc.GetSchemaRequest\x1a\x16.rpc.GetSchemaResponse\x12L\n" +
	"\x0fSupportsFeature\x12\x1b.rpc.SupportsFeatureRequest\x1a\x1c.rpc.SupportsFeatureResponseB0Z.github.com/mrtkrcm/ZeroUI/internal/plugins/rpcb\x06proto3"

var (
	file_internal_plugins_rpc_protocol_proto_rawDescOnce sync.Once
	file_internal_plugins_rpc_protocol_proto_rawDescData []byte
)

func file_internal_plugins_rpc_protocol_proto_rawDescGZIP() []byte {
	file_internal_plugins_rpc_protocol_proto_rawDescOnce.Do(func() {
		file_internal_plugins_rpc_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugins_rpc_protocol_proto_rawDesc), len(file_internal_plugins_rpc_protocol_proto_rawDesc)))
	})
	return file_internal_plugins_rpc_protocol_proto_rawDescData
}

var file_internal_plugins_rpc_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_internal_plugins_rpc_protocol_proto_goTypes = []any{
	(*GetInfoRequest)(nil),          // 0: rpc.GetInfoRequest
	(*GetInfoResponse)(nil),         // 1: rpc.GetInfoResponse
	(*DetectConfigRequest)(nil),     // 2: rpc.DetectConfigRequest
	(*DetectConfigResponse)(nil),    // 3: rpc.DetectConfigResponse
	(*ParseConfigRequest)(nil),      // 4: rpc.ParseConfigRequest
	(*ParseConfigResponse)(nil),     // 5: rpc.ParseConfigResponse
	(*WriteConfigRequest)(nil),      // 6: rpc.WriteConfigRequest
	(*WriteConfigResponse)(nil),     // 7: rpc.WriteConfigResponse
	(*ValidateFieldRequest)(nil),    // 8: rpc.ValidateFieldRequest
	(*ValidateFieldResponse)(nil),   // 9: rpc.ValidateFieldResponse
	(*ValidateConfigRequest)(nil),   // 10: rpc.ValidateConfigRequest
	(*ValidateConfigResponse)(nil),  // 11: rpc.ValidateConfigResponse
	(*GetSchemaRequest)(nil),        // 12: rpc.GetSchemaRequest
	(*GetSchemaResponse)(nil),       // 13: rpc.GetSchemaResponse
	(*SupportsFeatureRequest)(nil),  // 14: rpc.SupportsFeatureRequest
	(*SupportsFeatureResponse)(nil), // 15: rpc.SupportsFeatureResponse
	(*PluginInfo)(nil),              // 16: rpc.PluginInfo
	(*ConfigInfo)(nil),              // 17: rpc.ConfigInfo
	(*ConfigData)(nil),              // 18: rpc.ConfigData
	(*ConfigMetadata)(nil),          // 19: rpc.ConfigMetadata
	(*FieldMetadata)(nil),           // 20: rpc.FieldMetadata
	(*Validation)(nil),              // 21: rpc.Validation
	(*PresetData)(nil),              // 22: rpc.PresetData
	(*SchemaInfo)(nil),              // 23: rpc.SchemaInfo
	(*ValidationError)(nil),         // 24: rpc.ValidationError
	nil,                             // 25: rpc.PluginInfo.MetadataEntry
	nil,                             // 26: rpc.ConfigData.FieldsEntry
	nil,                             // 27: rpc.ConfigMetadata.FieldsEntry
	nil,                             // 28: rpc.ConfigMetadata.PresetsEntry
	nil,                             // 29: rpc.PresetData.ValuesEntry
	(*anypb.Any)(nil),               // 30: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),   // 31: google.protobuf.Timestamp
}
var file_internal_plugins_rpc_protocol_proto_depIdxs = []int32{
	16, // 0: rpc.GetInfoResponse.info:type_name -> rpc.PluginInfo
	17, // 1: rpc.DetectConfigResponse.config:type_name -> rpc.ConfigInfo
	18, // 2: rpc.ParseConfigResponse.data:type_name -> rpc.ConfigData
	18, // 3: rpc.WriteConfigRequest.data:type_name -> rpc.ConfigData
	30, // 4: rpc.ValidateFieldRequest.value:type_name -> google.protobuf.Any
	18, // 5: rpc.ValidateConfigRequest.data:type_name -> rpc.ConfigData
	24, // 6: rpc.ValidateConfigResponse.errors:type_name -> rpc.ValidationError
	19, // 7: rpc.GetSchemaResponse.metadata:type_name -> rpc.ConfigMetadata
	25, // 8: rpc.PluginInfo.metadata:type_name -> rpc.PluginInfo.MetadataEntry
	31, // 9: rpc.ConfigInfo.last_modified:type_name -> google.protobuf.Timestamp
	26, // 10: rpc.ConfigData.fields:type_name -> rpc.ConfigData.FieldsEntry
	19, // 11: rpc.ConfigData.metadata:type_name -> rpc.ConfigMetadata
	27, // 12: rpc.ConfigMetadata.fields:type_name -> rpc.ConfigMetadata.FieldsEntry
	28, // 13: rpc.ConfigMetadata.presets:type_name -> rpc.ConfigMetadata.PresetsEntry
	23, // 14: rpc.ConfigMetadata.schema:type_name -> rpc.SchemaInfo
	30, // 15: rpc.FieldMetadata.default_value:type_name -> google.protobuf.Any
	21, // 16: rpc.FieldMetadata.validation:type_name -> rpc.Validation
	30, // 17: rpc.Validation.min:type_name -> google.protobuf.Any
	30, // 18: rpc.Validation.max:type_name -> google.protobuf.Any
	29, // 19: rpc.PresetData.values:type_name -> rpc.PresetData.ValuesEntry
	30, // 20: rpc.ValidationError.value:type_name -> google.protobuf.Any
	30, // 21: rpc.ConfigData.FieldsEntry.value:type_name -> google.protobuf.Any
	20, // 22: rpc.ConfigMetadata.FieldsEntry.value:type_name -> rpc.FieldMetadata
	22, // 23: rpc.ConfigMetadata.PresetsEntry.value:type_name -> rpc.PresetData
	30, // 24: rpc.PresetData.ValuesEntry.value:type_name -> google.protobuf.Any
	0,  // 25: rpc.ConfigPlugin.GetInfo:input_type -> rpc.GetInfoRequest
	2,  // 26: rpc.ConfigPlugin.DetectConfig:input_type -> rpc.DetectConfigRequest
	4,  // 27: rpc.ConfigPlugin.ParseConfig:input_type -> rpc.ParseConfigRequest
	6,  // 28: rpc.ConfigPlugin.WriteConfig:input_type -> rpc.WriteConfigRequest
	8,  // 29: rpc.ConfigPlugin.ValidateField:input_type -> rpc.ValidateFieldRequest
	10, // 30: rpc.ConfigPlugin.ValidateConfig:input_type -> rpc.ValidateConfigRequest
	12, // 31: rpc.ConfigPlugin.GetSchema:input_type -> rpc.GetSchemaRequest
	14, // 32: rpc.ConfigPlugin.SupportsFeature:input_type -> rpc.SupportsFeatureRequest
	1,  // 33: rpc.ConfigPlugin.GetInfo:output_type -> rpc.GetInfoResponse
	3,  // 34: rpc.ConfigPlugin.DetectConfig:output_type -> rpc.DetectConfigResponse
	5,  // 35: rpc.ConfigPlugin.ParseConfig:output_type -> rpc.ParseConfigResponse
	7,  // 36: rpc.ConfigPlugin.WriteConfig:output_type -> rpc.WriteConfigResponse
	9,  // 37: rpc.ConfigPlugin.ValidateField:output_type -> rpc.ValidateFieldResponse
	11, // 38: rpc.ConfigPlugin.ValidateConfig:output_type -> rpc.ValidateConfigResponse
	13, // 39: rpc.ConfigPlugin.GetSchema:output_type -> rpc.GetSchemaResponse
	15, // 40: rpc.ConfigPlugin.SupportsFeature:output_type -> rpc.SupportsFeatureResponse
	33, // [33:41] is the sub-list for method output_type
	25, // [25:33] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_internal_plugins_rpc_protocol_proto_init() }
func file_internal_plugins_rpc_protocol_proto_init() {
	if File_internal_plugins_rpc_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugins_rpc_protocol_proto_rawDesc), len(file_internal_plugins_rpc_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_plugins_rpc_protocol_proto_goTypes,
		DependencyIndexes: file_internal_plugins_rpc_protocol_proto_depIdxs,
		MessageInfos:      file_internal_plugins_rpc_protocol_proto_msgTypes,
	}.Build()
	File_internal_plugins_rpc_protocol_proto = out.File
	file_internal_plugins_rpc_protocol_proto_goTypes = nil
	file_internal_plugins_rpc_protocol_proto_depIdxs = nil
}
